config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :slots
  resources :stations
  resources :titulos
  root 'site#index'

  resources :site


  
  resources :old_users

  resources :station
  
  post '/station/new(:station)'       => "station#create"

  resources :slot

  post '/slot/new(:slot)'       => "slot#create"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/old_user.rb
class OldUser < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/slot.rb
class Slot < ApplicationRecord
end

app/models/station.rb
class Station < ApplicationRecord
end

app/models/titulo.rb
class Titulo < ApplicationRecord
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/old_users_controller.rb
class OldUsersController < ApplicationController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :set_slot, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /slots
  # GET /slots.json
  def index
    @slots = Slot.all
  end

  # GET /slots/1
  # GET /slots/1.json
  def show
  end

  # GET /slots/new
  def new
    @slot = Slot.new
  end

  # GET /slots/1/edit
  def edit
  end

  # POST /slots
  # POST /slots.json
  def create
    @slot = Slot.new(slot_params)

    respond_to do |format|
      if @slot.save
        format.html { redirect_to @slot, notice: 'Slot was successfully created.' }
        format.json { render :show, status: :created, location: @slot }
      else
        format.html { render :new }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slots/1
  # PATCH/PUT /slots/1.json
  def update
    respond_to do |format|
      if @slot.update(slot_params)
        format.html { redirect_to @slot, notice: 'Slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @slot }
      else
        format.html { render :edit }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1
  # DELETE /slots/1.json
  def destroy
    @slot.destroy
    respond_to do |format|
      format.html { redirect_to slots_url, notice: 'Slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slot
      @slot = Slot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slot_params
      params.require(:slot).permit(:station_id, :name, :park)
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name, :latitude, :longitude, :active)
    end
end

app/controllers/titulos_controller.rb
class TitulosController < ApplicationController
  before_action :set_titulo, only: [:show, :edit, :update, :destroy]

  # GET /titulos
  # GET /titulos.json
  def index
    @titulos = Titulo.all
  end

  # GET /titulos/1
  # GET /titulos/1.json
  def show
  end

  # GET /titulos/new
  def new
    @titulo = Titulo.new
  end

  # GET /titulos/1/edit
  def edit
  end

  # POST /titulos
  # POST /titulos.json
  def create
    @titulo = Titulo.new(titulo_params)

    respond_to do |format|
      if @titulo.save
        format.html { redirect_to @titulo, notice: 'Titulo was successfully created.' }
        format.json { render :show, status: :created, location: @titulo }
      else
        format.html { render :new }
        format.json { render json: @titulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titulos/1
  # PATCH/PUT /titulos/1.json
  def update
    respond_to do |format|
      if @titulo.update(titulo_params)
        format.html { redirect_to @titulo, notice: 'Titulo was successfully updated.' }
        format.json { render :show, status: :ok, location: @titulo }
      else
        format.html { render :edit }
        format.json { render json: @titulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titulos/1
  # DELETE /titulos/1.json
  def destroy
    @titulo.destroy
    respond_to do |format|
      format.html { redirect_to titulos_url, notice: 'Titulo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_titulo
      @titulo = Titulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def titulo_params
      params.require(:titulo).permit(:titulo)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/old_users_helper.rb
module OldUsersHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/titulos_helper.rb
module TitulosHelper
end

app/views/old_users/index.html.erb
<h1>OldUsers#index</h1>
<p>Find me in app/views/old_users/index.html.erb</p>

app/views/site/index.html.erb
<h1>Site#index</h1>
<p>Find me in app/views/site/index.html.erb</p>

app/views/slots/_form.html.erb
<%= simple_form_for(@slot) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input  :station_id, label: 'Estação' ,collection: Station.all.collect { |p| [p.name, p.id] } , prompt: '' %>
    <%= f.input :name %>
    <%= f.input :qtd %>
    <%= f.input :park %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/slots/edit.html.erb
<h1>Editing Slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Show', @slot %> |
<%= link_to 'Back', slots_path %>

app/views/slots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Slots</h1>

<table>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Station</th>
        <th>Name</th>
        <th>Park</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  <thead>
    <tr>
      
    </tr>
  </thead>

  <tbody>
    <% @slots.each do |slot| %>
      <tr>
        <% s = Station.find(slot.station_id) %>
        <td><%= s.name %></td>
        <td><%= slot.name %></td>
        <td><%= slot.park %></td>
        <td><%= link_to 'Show', slot %></td>
        <td><%= link_to 'Edit', edit_slot_path(slot) %></td>
        <td><%= link_to 'Destroy', slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slot', new_slot_path %>

app/views/slots/new.html.erb
<h1>New Slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Back', slots_path %>

app/views/slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Station:</strong>
  <%= @slot.station_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @slot.name %>
</p>

<p>
  <strong>Park:</strong>
  <%= @slot.park %>
</p>

<%= link_to 'Edit', edit_slot_path(@slot) %> |
<%= link_to 'Back', slots_path %>

app/views/stations/_form.html.erb
<%= simple_form_for(@station) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.input :active %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.name %></td>
        <td><%= station.latitude %></td>
        <td><%= station.longitude %></td>
        <td><%= station.active %></td>
        <td><%= link_to 'Vis.', station %></td>
        <td><%= link_to 'Edit.', edit_station_path(station) %></td>
        <td><%#= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<table>
  <thead>
    

  
</table>

<br>

<%= link_to 'Nova Estação', new_station_path %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @station.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @station.longitude %>
</p>

<p>
  <strong>Active:</strong>
  <%= @station.active %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>

app/views/titulos/_form.html.erb
<%= simple_form_for(@titulo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :titulo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/titulos/edit.html.erb
<h1>Editing Titulo</h1>

<%= render 'form', titulo: @titulo %>

<%= link_to 'Show', @titulo %> |
<%= link_to 'Back', titulos_path %>

app/views/titulos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Titulos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @titulos.each do |titulo| %>
      <tr>
        <td><%= titulo.titulo %></td>
        <td><%= link_to 'Show', titulo %></td>
        <td><%= link_to 'Edit', edit_titulo_path(titulo) %></td>
        <td><%= link_to 'Destroy', titulo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Titulo', new_titulo_path %>

app/views/titulos/new.html.erb
<h1>New Titulo</h1>

<%= render 'form', titulo: @titulo %>

<%= link_to 'Back', titulos_path %>

app/views/titulos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @titulo.titulo %>
</p>

<%= link_to 'Edit', edit_titulo_path(@titulo) %> |
<%= link_to 'Back', titulos_path %>