config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :slots
  resources :stations
  resources :titulos
  root 'site#index'

  resources :site


  
  resources :old_users

  resources :station
  
  post '/station/new(:station)'       => "station#create"

  resources :slot

  post '/slot/new(:slot)'       => "slot#create"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/old_user.rb
class OldUser < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/slot.rb
class Slot < ApplicationRecord
end

app/models/station.rb
class Station < ApplicationRecord
end

app/models/titulo.rb
class Titulo < ApplicationRecord
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
  end
end

app/controllers/old_users_controller.rb
class OldUsersController < ApplicationController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :set_slot, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /slots
  # GET /slots.json
  def index
    @slots = Slot.all
  end

  # GET /slots/1
  # GET /slots/1.json
  def show
  end

  # GET /slots/new
  def new
    @slot = Slot.new
  end

  # GET /slots/1/edit
  def edit
  end

  # POST /slots
  # POST /slots.json
  def create
    @slot = Slot.new(slot_params)

    respond_to do |format|
      if @slot.save
        format.html { redirect_to @slot, notice: 'Slot was successfully created.' }
        format.json { render :show, status: :created, location: @slot }
      else
        format.html { render :new }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slots/1
  # PATCH/PUT /slots/1.json
  def update
    respond_to do |format|
      if @slot.update(slot_params)
        format.html { redirect_to @slot, notice: 'Slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @slot }
      else
        format.html { render :edit }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1
  # DELETE /slots/1.json
  def destroy
    @slot.destroy
    respond_to do |format|
      format.html { redirect_to slots_url, notice: 'Slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slot
      @slot = Slot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slot_params
      params.require(:slot).permit(:station_id, :name, :park)
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name, :latitude, :longitude, :active)
    end
end

app/controllers/titulos_controller.rb
class TitulosController < ApplicationController
  before_action :set_titulo, only: [:show, :edit, :update, :destroy]

  # GET /titulos
  # GET /titulos.json
  def index
    @titulos = Titulo.all
  end

  # GET /titulos/1
  # GET /titulos/1.json
  def show
  end

  # GET /titulos/new
  def new
    @titulo = Titulo.new
  end

  # GET /titulos/1/edit
  def edit
  end

  # POST /titulos
  # POST /titulos.json
  def create
    @titulo = Titulo.new(titulo_params)

    respond_to do |format|
      if @titulo.save
        format.html { redirect_to @titulo, notice: 'Titulo was successfully created.' }
        format.json { render :show, status: :created, location: @titulo }
      else
        format.html { render :new }
        format.json { render json: @titulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titulos/1
  # PATCH/PUT /titulos/1.json
  def update
    respond_to do |format|
      if @titulo.update(titulo_params)
        format.html { redirect_to @titulo, notice: 'Titulo was successfully updated.' }
        format.json { render :show, status: :ok, location: @titulo }
      else
        format.html { render :edit }
        format.json { render json: @titulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titulos/1
  # DELETE /titulos/1.json
  def destroy
    @titulo.destroy
    respond_to do |format|
      format.html { redirect_to titulos_url, notice: 'Titulo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_titulo
      @titulo = Titulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def titulo_params
      params.require(:titulo).permit(:titulo)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/old_users_helper.rb
module OldUsersHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/titulos_helper.rb
module TitulosHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>
<%- if devise_mapping.registerable? && controller_name != 'registrations' && admin_signed_in?%>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tembike</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= render partial: '/menu' %>
    
    
    

    <!-- Page Content -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 text-center">
              <br><br><br><br><br><br>
                <%= yield %>
            </div>
        </div>
    </div>
  </body>
</html>